export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const LOGOUT_USER_SUCCESSFULLY = 'LOGOUT_USER_SUCCESSFULLY';
export const REGISTER_USER_SUCCESSFULLY = "REGISTER_USER_SUCCESSFULLY";
export const GET_CONVERSATION_MESSAGES = 'GET_CONVERSATION_MESSAGES';
export const GET_CHAT_MESSAGE = 'GET_CHAT_MESSAGE';
export const GET_ONLINE_USERS = 'GET_ONLINE_USERS';
